apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-js-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-js-app
  template:
    metadata:
      labels:
        app: simple-js-app
    spec:
      containers:
      - name: simple-js-app
        image: 473550160103.dkr.ecr.eu-north-1.amazonaws.com/simple-js-app:latest
        
        ports:
        - containerPort: 3000