name: Deploy to AWS EKS with Terraform

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1           # Your AWS region
  IMAGE_REPO: simple-js-app        # Your ECR repository name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 0️⃣: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1️⃣: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 2️⃣: Terraform init and get EKS cluster name
      - name: Terraform Init & Output
        run: |
          cd terraform
          terraform init
          CLUSTER_NAME=$(terraform output -raw eks_cluster_name)
          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV

      # Step 3️⃣: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4️⃣: Build and tag Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker build -t $ECR_REGISTRY/${{ env.IMAGE_REPO }}:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/${{ env.IMAGE_REPO }}:$IMAGE_TAG $ECR_REGISTRY/${{ env.IMAGE_REPO }}:latest

      # Step 5️⃣: Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker push $ECR_REGISTRY/${{ env.IMAGE_REPO }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ env.IMAGE_REPO }}:latest

      # Step 6️⃣: Update kubeconfig to connect to EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region ${{ env.AWS_REGION }}

      # Step 7️⃣: Deploy updated image to EKS
      - name: Deploy to EKS
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          kubectl set image deployment/simple-js-app simple-js-app=$ECR_REGISTRY/${{ env.IMAGE_REPO }}:$IMAGE_TAG
