name: Deploy to AWS EKS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1               # Your AWS region
  IMAGE_REPO: simple-js-app            # Your ECR repository name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 0️⃣: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1️⃣: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 2️⃣: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      # Step 3️⃣: Terraform Init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 4️⃣: Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      # Step 5️⃣: Terraform Apply
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      # Step 6️⃣: Update kubeconfig to connect to your EKS cluster
      - name: Update kubeconfig
        run: |
          CLUSTER_NAME=$(terraform -chdir=terraform output -raw eks_cluster_name)
          aws eks update-kubeconfig --name $CLUSTER_NAME --region ${{ env.AWS_REGION }}

      # Step 7️⃣: Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=$(terraform -chdir=terraform output -raw ecr_repository_uri)
          docker build -t $ECR_REGISTRY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY:$IMAGE_TAG $ECR_REGISTRY:latest

      # Step 8️⃣: Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=$(terraform -chdir=terraform output -raw ecr_repository_uri)
          docker push $ECR_REGISTRY:$IMAGE_TAG
          docker push $ECR_REGISTRY:latest

      # Step 9️⃣: Deploy updated Docker image to EKS
      - name: Deploy to EKS
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=$(terraform -chdir=terraform output -raw ecr_repository_uri)
          kubectl set image deployment/simple-js-app simple-js-app=$ECR_REGISTRY:$IMAGE_TAG
